name: CI/CD

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Build our own libvips with HEIC support so that sharp will use that
      # https://github.com/libvips/libvips/wiki/Build-for-Ubuntu
      # https://github.com/libvips/libvips/issues/1511
#      - name: install libcgif
#        run: sudo add-apt-repository ppa:lovell/cgif && sudo apt-get update && sudo apt-get install libcgif-dev
      - name: Install libvips dependencies
        run: sudo apt-get update && sudo apt-get install -y libcgif-dev libheif-dev libfftw3-dev libopenexr-dev libgsf-1-dev libglib2.0-dev libglib2.0-0 liborc-dev libopenslide-dev libmatio-dev libwebp-dev libjpeg-turbo8-dev libexpat1-dev libexif-dev libtiff5-dev libcfitsio-dev libpoppler-glib-dev librsvg2-dev libpango1.0-dev libopenjp2-7-dev libimagequant-dev
      - name: Install build tools
        run: sudo apt-get install build-essential ninja-build python3-pip bc wget
      - name: Remove system libvips
        run: sudo apt-get remove libvips42
      - name: Build libvips with HEIC support
        run: |
          pip3 install meson
          export PATH=$PATH:/home/runner/.local/bin
          wget https://github.com/libvips/libvips/releases/download/v8.15.0/vips-8.15.0.tar.xz
          tar xf vips-8.15.0.tar.xz
          cd vips-8.15.0
          meson build --libdir=lib --buildtype=release -Dintrospection=disabled
          cd build
          meson compile
          meson test
          sudo pip3 install meson
          sudo meson install
      - name: NPM install
        run: npm run clean:install
        working-directory: source/constructs
#      - run: npm uninstall sharp
#        working-directory: source/constructs
#      - run: pkg-config --modversion vips-cpp
#      - run: npm install --verbose --arch=x64 --platform=linux --foreground-scripts --no-cache sharp@0.32.6
#        working-directory: source/constructs
      - run: ldd /usr/local/lib/libvips.so.42
      - run: ldd /usr/local/lib/libvips-cpp.so.42
      - run: ldd /lib/x86_64-linux-gnu/libm.so.6
      - name: Create lib layer for lambda
        run: | 
          mkdir lib
          cp /usr/local/lib/libvips.so.42 lib/
          cp /usr/local/lib/libvips-cpp.so.42 lib/
          cp /lib/x86_64-linux-gnu/libHalf-2_5.so.25 lib/
          cp /lib/x86_64-linux-gnu/libIex-2_5.so.25 lib/
          cp /lib/x86_64-linux-gnu/libIlmImf-2_5.so.25 lib/
          cp /lib/x86_64-linux-gnu/libIlmImfUtil-2_5.so.25 lib/
          cp /lib/x86_64-linux-gnu/libIlmThread-2_5.so.25 lib/
          cp /lib/x86_64-linux-gnu/libImath-2_5.so.25 lib/
          cp /lib/x86_64-linux-gnu/libX11.so.6 lib/
          cp /lib/x86_64-linux-gnu/libXau.so.6 lib/
          cp /lib/x86_64-linux-gnu/libXdmcp.so.6 lib/
          cp /lib/x86_64-linux-gnu/libXext.so.6 lib/
          cp /lib/x86_64-linux-gnu/libXrender.so.1 lib/
          cp /lib/x86_64-linux-gnu/libaec.so.0 lib/
          cp /lib/x86_64-linux-gnu/libblkid.so.1 lib/
          cp /lib/x86_64-linux-gnu/libbrotlicommon.so.1 lib/
          cp /lib/x86_64-linux-gnu/libbrotlidec.so.1 lib/
          cp /lib/x86_64-linux-gnu/libbsd.so.0 lib/
          cp /lib/x86_64-linux-gnu/libbz2.so.1.0 lib/
          cp /lib/x86_64-linux-gnu/libc.so.6 lib/
          cp /lib/x86_64-linux-gnu/libcairo-gobject.so.2 lib/
          cp /lib/x86_64-linux-gnu/libcairo.so.2 lib/
          cp /lib/x86_64-linux-gnu/libcfitsio.so.9 lib/
          cp /lib/x86_64-linux-gnu/libcgif.so.0 lib/
          cp /lib/x86_64-linux-gnu/libcom_err.so.2 lib/
          cp /lib/x86_64-linux-gnu/libcrypt.so.1 lib/
          cp /lib/x86_64-linux-gnu/libcrypto.so.1.1 lib/
          cp /lib/x86_64-linux-gnu/libcrypto.so.3 lib/
          cp /lib/x86_64-linux-gnu/libcurl.so.4 lib/
          cp /lib/x86_64-linux-gnu/libcurl-gnutls.so.4 lib/
          cp /lib/x86_64-linux-gnu/libdatrie.so.1 lib/
          cp /lib/x86_64-linux-gnu/libdeflate.so.0 lib/
          cp /lib/x86_64-linux-gnu/libdl.so.2 lib/
          cp /lib/x86_64-linux-gnu/libexif.so.12 lib/
          cp /lib/x86_64-linux-gnu/libexpat.so.1 lib/
          cp /lib/x86_64-linux-gnu/libffi.so.8 lib/
          cp /lib/x86_64-linux-gnu/libfftw3.so.3 lib/
          cp /lib/x86_64-linux-gnu/libfftw3_omp.so.3 lib/
          cp /lib/x86_64-linux-gnu/libfftw3_threads.so.3 lib/
          cp /lib/x86_64-linux-gnu/libfontconfig.so.1 lib/
          cp /lib/x86_64-linux-gnu/libfreetype.so.6 lib/
          cp /lib/x86_64-linux-gnu/libfribidi.so.0 lib/
          cp /lib/x86_64-linux-gnu/libgcc_s.so.1 lib/
          cp /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 lib/
          cp /lib/x86_64-linux-gnu/libgio-2.0.so.0 lib/
          cp /lib/x86_64-linux-gnu/libglib-2.0.so.0 lib/
          cp /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 lib/
          cp /lib/x86_64-linux-gnu/libgmp.so.10 lib/
          cp /lib/x86_64-linux-gnu/libgnutls.so.30 lib/
          cp /lib/x86_64-linux-gnu/libgobject-2.0.so.0 lib/
          cp /lib/x86_64-linux-gnu/libgomp.so.1 lib/
          cp /lib/x86_64-linux-gnu/libgraphite2.so.3 lib/
          cp /lib/x86_64-linux-gnu/libgsf-1.so.114 lib/
          cp /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 lib/
          cp /lib/x86_64-linux-gnu/libharfbuzz.so.0 lib/
          cp /lib/x86_64-linux-gnu/libhdf5_serial.so.103 lib/
          cp /lib/x86_64-linux-gnu/libheif.so.1 lib/
          cp /lib/x86_64-linux-gnu/libhogweed.so.6 lib/
          cp /lib/x86_64-linux-gnu/libicudata.so.70 lib/
          cp /lib/x86_64-linux-gnu/libicuuc.so.70 lib/
          cp /lib/x86_64-linux-gnu/libidn2.so.0 lib/
          cp /lib/x86_64-linux-gnu/libimagequant.so.0 lib/
          cp /lib/x86_64-linux-gnu/libjbig.so.0 lib/
          cp /lib/x86_64-linux-gnu/libjpeg.so.8 lib/
          cp /lib/x86_64-linux-gnu/libk5crypto.so.3 lib/
          cp /lib/x86_64-linux-gnu/libkeyutils.so.1 lib/
          cp /lib/x86_64-linux-gnu/libkrb5.so.3 lib/
          cp /lib/x86_64-linux-gnu/libkrb5support.so.0 lib/
          cp /lib/x86_64-linux-gnu/liblber-2.5.so.0 lib/
          cp /lib/x86_64-linux-gnu/liblcms2.so.2 lib/
          cp /lib/x86_64-linux-gnu/libldap-2.5.so.0 lib/
          cp /lib/x86_64-linux-gnu/liblzma.so.5 lib/
          cp /lib/x86_64-linux-gnu/libm.so.6 lib/
          cp /lib/x86_64-linux-gnu/libmatio.so.11 lib/
          cp /lib/x86_64-linux-gnu/libmount.so.1 lib/
          cp /lib/x86_64-linux-gnu/libnettle.so.8 lib/
          cp /lib/x86_64-linux-gnu/libnghttp2.so.14 lib/
          cp /lib/x86_64-linux-gnu/libopenjp2.so.7 lib/
          cp /lib/x86_64-linux-gnu/libopenslide.so.0 lib/
          cp /lib/x86_64-linux-gnu/liborc-0.4.so.0 lib/
          cp /lib/x86_64-linux-gnu/libp11-kit.so.0 lib/
          cp /lib/x86_64-linux-gnu/libpango-1.0.so.0 lib/
          cp /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 lib/
          cp /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 lib/
          cp /lib/x86_64-linux-gnu/libpangoxft-1.0.so.0 lib/
          cp /lib/x86_64-linux-gnu/libpcre.so.3 lib/
          cp /lib/x86_64-linux-gnu/libpcre2-8.so.0 lib/
          cp /lib/x86_64-linux-gnu/libpixman-1.so.0 lib/
          cp /lib/x86_64-linux-gnu/libpng16.so.16 lib/
          cp /lib/x86_64-linux-gnu/libpsl.so.5 lib/
          cp /lib/x86_64-linux-gnu/libpthread.so.0 lib/
          cp /lib/x86_64-linux-gnu/libresolv.so.2 lib/
          cp /lib/x86_64-linux-gnu/librsvg-2.so.2 lib/
          cp /lib/x86_64-linux-gnu/librtmp.so.1 lib/
          cp /lib/x86_64-linux-gnu/libsasl2.so.2 lib/
          cp /lib/x86_64-linux-gnu/libselinux.so.1 lib/
          cp /lib/x86_64-linux-gnu/libsqlite3.so.0 lib/
          cp /lib/x86_64-linux-gnu/libssh.so.4 lib/
          cp /lib/x86_64-linux-gnu/libssl.so.3 lib/
          cp /lib/x86_64-linux-gnu/libstdc++.so.6 lib/
          cp /lib/x86_64-linux-gnu/libsz.so.2 lib/
          cp /lib/x86_64-linux-gnu/libtasn1.so.6 lib/
          cp /lib/x86_64-linux-gnu/libthai.so.0 lib/
          cp /lib/x86_64-linux-gnu/libtiff.so.5 lib/
          cp /lib/x86_64-linux-gnu/libunistring.so.2 lib/
          cp /lib/x86_64-linux-gnu/libuuid.so.1 lib/
          cp /lib/x86_64-linux-gnu/libwebp.so.7 lib/
          cp /lib/x86_64-linux-gnu/libwebpdemux.so.2 lib/
          cp /lib/x86_64-linux-gnu/libwebpmux.so.3 lib/
          cp /lib/x86_64-linux-gnu/libxcb-render.so.0 lib/
          cp /lib/x86_64-linux-gnu/libxcb-shm.so.0 lib/
          cp /lib/x86_64-linux-gnu/libxcb.so.1 lib/
          cp /lib/x86_64-linux-gnu/libxml2.so.2 lib/
          cp /lib/x86_64-linux-gnu/libz.so.1 lib/
          cp /lib/x86_64-linux-gnu/libzstd.so.1 lib/
          zip -r libvips-layer.zip lib
        working-directory: source/constructs/lib/back-end

      # Deploy cloudformation stack with CDK
      - name: Set QA Environment
        if: github.base_ref == 'qa'
        run: |
          echo "STAGE=qa" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.LOWER_ENV_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.LOWER_ENV_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "SOURCE_BUCKET=mslc-player-qa-document-upload" >> $GITHUB_ENV
          echo "S3_KMS_KEY_ARN=arn:aws:kms:us-east-1:963973445526:key/9ea6ef14-c12a-42c6-9e6d-56cc0f389bb4" >> $GITHUB_ENV
          echo "SIGNING_SECRET=mslc-document-upload-qa" >> $GITHUB_ENV
      - name: Set UAT Environment
        if: github.base_ref == 'uat'
        run: |
          echo "STAGE=uat" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.LOWER_ENV_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.LOWER_ENV_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "SOURCE_BUCKET=mslc-player-uat-document-upload" >> $GITHUB_ENV
          echo "S3_KMS_KEY_ARN=arn:aws:kms:us-east-1:963973445526:key/60c48e18-9e6c-4f74-84c7-5241fd45eca3" >> $GITHUB_ENV
          echo "SIGNING_SECRET=mslc-document-upload-uat" >> $GITHUB_ENV
      - name: Set Prod Environment
        if: github.base_ref == 'master'
        run: |
          echo "STAGE=prod" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.PROD_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
      - name: Deploy Stack
        run: overrideWarningsEnabled=false npx cdk deploy --parameters CorsEnabledParameter=Yes --parameters CorsOriginParameter='*' --parameters SourceBucketsParameter=${{ env.SOURCE_BUCKET }} --parameters DeployDemoUIParameter=No --parameters EnableSignatureParameter=Yes --parameters SecretsManagerSecretParameter=${{ env.SIGNING_SECRET }} --parameters SecretsManagerKeyParameter=SECRET_KEY --parameters S3KmsKeyArnParameter="${{ env.S3_KMS_KEY_ARN }}" --context stackName=mslc-document-upload-image-handler-${{ env.STAGE }}
        working-directory: source/constructs